/**:
  ros__parameters:
    uav_mass: 1.5
    antiwindup_cte : 1.0
    alpha: 0.1
    speed_controller:
      speed_Kp: 
        x: 3.0
        y: 3.0
        z: 4.0
      speed_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
      speed_Ki:
        x: 0.0
        y: 0.0
        z: 0.01
    angular_speed_controller:
      angular_gain:
        x: 5.5
        y: 5.5
        z: 5.0 
